# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmUzN2FmYzRjMjM3MDBhNGI2OTQyMjRkMDBiMzFhYWZhMDY0MDZhMTJjNzk2M2EzMzFmOTc3NGYyYTRjZDA3MThhZjU4ODcxN2MwNjMxMDgxNTA2MDNmMDM1NTI1MzEyY2M2OWVmYmJiYTcxNTFiNjBiNDgxODUxYmUzMjgyNGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
